### ISSUE TITLE
An error occoured

### ISSUE THREAD

**Issue by enterih** [WolverinDEV/BungeeUtil#14] opened 2016-12-07 01:02 UTC
Hi. Today I installed your plugin. The console will spamming with this error. I don't know why it's happen.

Im Using the newest BungeeUtilsversion
Bungeecord Build 1210
The server is running on a 64bit Windows Server 2012 Dedicated Server

01:54:32 [INFORMATION] An error happed. .RuntimeException message -> Packet error (Version: v1_11_0, Readed version: v1_11, Class: dev.wolveringer.bungeeutil.packets.PacketPlayOutNamedEntitySpawn, Id: 0x5) -> Cant find datawatcher for v1_11
01:54:32 [SCHWERWIEGEND] java.lang.RuntimeException: Packet error (Version: v1_11_0, Readed version: v1_11, Class: dev.wolveringer.bungeeutil.packets.PacketPlayOutNamedEntitySpawn, Id: 0x5) -> Cant find datawatcher for v1_11
01:54:32 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.entity.datawatcher.DataWatcher.createDataWatcher(DataWatcher.java:24)
01:54:32 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.packets.PacketPlayOutNamedEntitySpawn.read(PacketPlayOutNamedEntitySpawn.java:81)
01:54:32 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.packets.Packet.load(Packet.java:254)
01:54:32 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.packets.NormalPacketCreator.getPacket0(NormalPacketCreator.java:100)
01:54:32 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.packets.AbstractPacketCreator.getPacket(AbstractPacketCreator.java:58)
01:54:32 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.packets.Packet.getPacket(Packet.java:152)
01:54:32 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:117)
01:54:32 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:29)
01:54:32 [SCHWERWIEGEND] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
01:54:32 [SCHWERWIEGEND] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
01:54:32 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
01:54:32 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
01:54:32 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
01:54:32 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
01:54:32 [SCHWERWIEGEND] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
01:54:32 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
01:54:32 [SCHWERWIEGEND] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
01:54:32 [SCHWERWIEGEND] 	at java.lang.Thread.run(Unknown Source)

**Comment by enterih** [comment] 2016-12-07 01:07
I has temporary disable your plugin because I player are invisible.

Errorspam starting on joining server

**Comment by WolverinDEV** [comment] 2016-12-07 14:58
Hey just a few quick questions:
1. Do you use ViaVersion? If true when where do you use it? On the spigot/bukkit server or on the BungeeCord?
2. Minecraft server version?
3. With witch client version happens this error?

PS: A little tip: For better error code formatting paste the exception on hastebin or put it in "```" braces like this:
```
error
stack[0]
stack[1]
stack[2]
----
```

**Comment by enterih** [comment] 2016-12-07 16:37
Hey  
1. I found it on a server. I will delete and test it again, i'll tell later.
2. 1.11
3. 1.11 because only 1.11 is joinable

PS: Thanks. 😀

**Comment by JonathanVil** [comment] 2016-12-07 17:07
I get the same error. Will this mean that BungeeUtil is not combatible with cross-version plugins (ViaVersion), and can't be used with them at all?

**Comment by WolverinDEV** [comment] 2016-12-07 17:28
I will release the fix after im finishing eating

**Comment by WolverinDEV** [comment] 2016-12-07 17:49
Bug fixed in 2.0.1 :)

**Closed as completed by WolverinDEV** 2016-12-07 17:49 UTC
Labels: bug, fixed

**Comment by WolverinDEV** [comment] 2016-12-07 17:52
@JonathanVil 
BungeeUtil is compatible with cross-version plugins like ViaVersion.
The best way is to install ViaVersion on the server. I think if you have viaversion installed on the BungeeCord it will works too but im not shure

**Comment by JonathanVil** [comment] 2016-12-07 21:16
Well, then why does it print that error every second when a player is connected through another client version than the server?

**Comment by WolverinDEV** [comment] 2016-12-07 21:23
the problem is that im forgot to register the EntityDataWatcher for the 1.11 :)

**Comment by enterih** [comment] 2016-12-08 00:23
Cool :) It's amazing that you fix it in this short time. A lot of developer will wait many years to fix a report a bug.

Could you update it on spigot?  :D

**Comment by WolverinDEV** [comment] 2016-12-08 14:59
Thanks,
and i know how you feel. I know about a lots of devs who dont update or fix they published recourses.
But i think its important and much more important if its an plugin like this who is maybe a essential dependency and maybe for a whole server.

Im only updating my plugins on spigot if i added a new version.
I think everyone should enable the updater (min once at startup) to get the newest version :)

PS: If you like my plugin than i will be verry happy about a (good) review :P 
PPS: If you have any questions: Dont be to shy to ask!
